### ISSUE TITLE
Не работает на МЦК

### ISSUE THREAD

**Issue by yellow-sky** [TheDrHax/mosmetro-auth#11]
(

**Comment by TheDrHax** [comment]
Проблема может быть в чём угодно: изменение алгоритма (вчера было замечено изменение адреса на mcc.wi-fi.ru, но данные собрать не удалось), неисправность сети (на МЦК это происходит часто), или просто какая-то случайная ошибка...

Вы бы хоть лог подключения приложили для ясности, а то получается реально много вариантов.

**Comment by yellow-sky** [comment]
Ошибка всегда одна и та же:

```
2016-11-22 21:56:32.298695
Wrong network
```

**Comment by TheDrHax** [comment]
Проект надо полностью переписывать. Он создавался ещё тогда, когда в каждой сети был IP 1.1.1.1. У меня сейчас времени нет, к сожалению...

**Comment by TheDrHax** [comment]
Полностью переписал скрипт. Закрываю все тикеты по старому, так как тут будут уже свои проблемы. Переоткройте, если скрипт ещё нужен и внезапно не заработает на МЦК ;)

**Comment by yellow-sky** [comment]
Спасибо!

5 окт. 2017 г. 9:46 PM пользователь "Дмитрий Карих" <
notifications@github.com> написал:
