### ISSUE TITLE
Any plans to enhance the script?

### ISSUE THREAD

**Issue by PTikhonov** [TheDrHax/mosmetro-auth#12]
Since provider now detects "fraud" )) will you try to enhance the script?

Thanks for the effort anyway.

**Comment by TheDrHax** [comment]
I don't have much time at the moment. But I plan to rewrite it in the future ;)

**Comment by TheDrHax** [comment]
Project is now up to date with the latest version of MosMetroV2 algorithm from [mosmetro-android](https://github.com/mosmetro-android/mosmetro-android).
