### ISSUE TITLE
Не работает в метро на MT_FREE

### ISSUE THREAD

**Issue by petRUShka** [TheDrHax/mosmetro-auth#17]
Пишет:

```
Wrong network
```

При этом, если убрать соответсвующий `if`, пишет:

```
Detected provider: MosMetroV2
Parsing initial redirect
Following initial redirect
Traceback (most recent call last):
  File "__main__.py", line 137, in <module>
    main()
  File "__main__.py", line 129, in main
    if p.connect():
  File "__main__.py", line 81, in connect
    r = session.get(redirect.geturl(), allow_redirects=False)
NameError: name 'session' is not defined
```

В браузере авторизация проходит на ура.

**Comment by TheDrHax** [comment]
Сегодня (т.е. вчера) как раз исправил обе эти проблемы в коммите https://github.com/mosmetro-android/mosmetro-python/commit/f4fde2764642fe7a7f9083465407c36f546dbd4e

Там ещё неправильный метод запроса авторизации был (GET вместо POST), но его я проверить не успел, пока ехал. Планирую завтра (т.е. сегодня) продолжить тестирование.

Спасибо за тест :)

**Comment by petRUShka** [comment]
Что ж, попробуем :)
