### ISSUE TITLE
Проверка подключения зависит от стороннего сайта

### ISSUE THREAD

**Issue by festinuz** [TheDrHax/mosmetro-auth#7]
Вывод сообщения об успешном подлючении сети зависит от доступности сайта https://wtfismyip.com/text
Соответственно, в случае, если сайт недоступен, программа будет работать некоректно:
Сообщение об успешном подключении отображаться не будет.

**Comment by TheDrHax** [comment]
Есть ли у вас какие-нибудь идеи, как проверить наличие подключения к интернету?

В [Java-версии](https://github.com/TheDrHax/mosmetro-android/blob/master/src/pw/thedrhax/mosmetro/authenticator/AuthenticatorStat.java) проверка идет через мой сервер, попутно записывая статистику. Но собственный сервер тоже не вечен.

А wtfismyip использовался потому, что сеть подменяет сертификаты и, если подключения нет, страница по HTTPS не загрузится.

Можно попробовать проверять наличие перенаправления на страницу авторизации при переходе на, например, vmet.ro. Посмотрю, что можно сделать.

**Comment by festinuz** [comment]
> Можно попробовать проверять наличие перенаправления на страницу авторизации при переходе на vmet.ro. 

На удивление хороший вариант, двумя руками за него. Так как vmet.ro - часть сервиса, то данное решение проблемы выглядит оптимально.

**Comment by TheDrHax** [comment]
Нужно тщательнее проверить работоспособность этой проверки в разных условиях, но, на первый взгляд, проверка путем поиска редиректа оказалась достаточно эффективной.
